services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/java/io/github/pilzi/database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      TZ: Europe/Berlin
      DISCORD_API_KEY: ${DISCORD_API_KEY}
      HENRIKDEV_API_KEY: ${HENRIKDEV_API_KEY}
      VALORANT_REGION: ${VALORANT_REGION}
      POLL_CHANNEL_NAME: ${POLL_CHANNEL_NAME}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata: